# This file is for running the application locally

services:

  web:
    image: gbif/hp-sbdi-dev
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/site
